name: Regionerator
main: com.github.jikoo.regionerator.Regionerator
version: ${project.version}
api-version: "1.13"
author: Jikoo
softdepend:
- Civs
- Factions
- GriefDefender
- GriefPrevention
- Lands
- PreciousStones
- Multiverse-Core
- RedProtect
- Residence
- Towny
- WorldGuard

commands:
 regionerator:
  aliases: [regeninfo, rgr]
  description: Check Regionerator's progress, stop/start, or reload configuration.
  permission: regionerator.command
  usage: /regionerator [pause|resume|reload|(un)flag|check|cache] (no args for a report)
